// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: engines.proto

package engines

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int32 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (x *CarIdRequest) Reset() {
	*x = CarIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engines_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarIdRequest) ProtoMessage() {}

func (x *CarIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engines_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarIdRequest.ProtoReflect.Descriptor instead.
func (*CarIdRequest) Descriptor() ([]byte, []int) {
	return file_engines_proto_rawDescGZIP(), []int{0}
}

func (x *CarIdRequest) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

type EngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" redis:"id"`    // @gotags: redis:"id"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" redis:"name"` // @gotags: redis:"name"
}

func (x *EngineResponse) Reset() {
	*x = EngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engines_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineResponse) ProtoMessage() {}

func (x *EngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engines_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineResponse.ProtoReflect.Descriptor instead.
func (*EngineResponse) Descriptor() ([]byte, []int) {
	return file_engines_proto_rawDescGZIP(), []int{1}
}

func (x *EngineResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EngineResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnginesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Engines []*EngineResponse `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty" redis:"engines"` // @gotags: redis:"engines"
}

func (x *EnginesResponse) Reset() {
	*x = EnginesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engines_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnginesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnginesResponse) ProtoMessage() {}

func (x *EnginesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engines_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnginesResponse.ProtoReflect.Descriptor instead.
func (*EnginesResponse) Descriptor() ([]byte, []int) {
	return file_engines_proto_rawDescGZIP(), []int{2}
}

func (x *EnginesResponse) GetEngines() []*EngineResponse {
	if x != nil {
		return x.Engines
	}
	return nil
}

var File_engines_proto protoreflect.FileDescriptor

var file_engines_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x42, 0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0e,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x44, 0x0a, 0x0f, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73,
	0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x07, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x32, 0x4f, 0x0a, 0x06, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x12, 0x45, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73,
	0x42, 0x79, 0x43, 0x61, 0x72, 0x73, 0x49, 0x64, 0x12, 0x15, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x3b, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engines_proto_rawDescOnce sync.Once
	file_engines_proto_rawDescData = file_engines_proto_rawDesc
)

func file_engines_proto_rawDescGZIP() []byte {
	file_engines_proto_rawDescOnce.Do(func() {
		file_engines_proto_rawDescData = protoimpl.X.CompressGZIP(file_engines_proto_rawDescData)
	})
	return file_engines_proto_rawDescData
}

var file_engines_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_engines_proto_goTypes = []interface{}{
	(*CarIdRequest)(nil),    // 0: engines.CarIdRequest
	(*EngineResponse)(nil),  // 1: engines.EngineResponse
	(*EnginesResponse)(nil), // 2: engines.EnginesResponse
}
var file_engines_proto_depIdxs = []int32{
	1, // 0: engines.EnginesResponse.engines:type_name -> engines.EngineResponse
	0, // 1: engines.Engine.GetEnginesByCarsId:input_type -> engines.CarIdRequest
	2, // 2: engines.Engine.GetEnginesByCarsId:output_type -> engines.EnginesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engines_proto_init() }
func file_engines_proto_init() {
	if File_engines_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engines_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engines_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engines_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnginesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engines_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engines_proto_goTypes,
		DependencyIndexes: file_engines_proto_depIdxs,
		MessageInfos:      file_engines_proto_msgTypes,
	}.Build()
	File_engines_proto = out.File
	file_engines_proto_rawDesc = nil
	file_engines_proto_goTypes = nil
	file_engines_proto_depIdxs = nil
}
